/**
 * English display labels for Access Navigation Pane form names.
 * Object names stay German (MDB fidelity); UI labels follow Access EN captions.
 */

const EXACT: Record<string, string> = {
  "An Anolyt": "Anolyte Analysis",
  "An Anolyt Element": "Anolyte Analysis Element",
  "An Anolyt Gesamt": "Anolyte Analysis Plant",
  "An Anolyt Gruppe": "Anolyte Analysis Group",
  "An Anolyt Teilanlage": "Anolyte Analysis Sub-Plant",
  "An Caustic feed": "Caustic Feed Analysis",
  "An Caustic feed Teilanlage": "Caustic Feed Analysis Sub-Plant",
  "An Chlorgas": "Chlorine Gas Analysis",
  "An Chlorgas Element": "Chlorine Gas Analysis Element",
  "An Chlorgas Gesamt": "Chlorine Gas Analysis Plant",
  "An Chlorgas Gruppe": "Chlorine Gas Analysis Group",
  "An Chlorgas Teilanlage": "Chlorine Gas Analysis Sub-Plant",
  "An Deminwater": "Demin. Water Analysis",
  "An HCl": "HCl Analysis",
  "An HCl Gesamt": "HCl Analysis Plant",
  "An Hydrogen": "Hydrogen Analysis",
  "An Katholyt": "Catholyte Analysis",
  "An Katholyt Element": "Catholyte Analysis Element",
  "An Katholyt Gesamt": "Catholyte Analysis Plant",
  "An Katholyt Gruppe": "Catholyte Analysis Group",
  "An Katholyt Teilanlage": "Catholyte Analysis Sub-Plant",
  "An Reinsole": "Pure Brine Analysis",
  "An Reinsole Element": "Pure Brine Analysis Element",
  "An Reinsole Gesamt": "Pure Brine Analysis Plant",
  "An Reinsole Gruppe": "Pure Brine Analysis Group",
  "An Reinsole Teilanlage": "Pure Brine Analysis Sub-Plant",
  "An StromAusGes": "Current Efficiency Plant",
  Analyse: "Analyses",
  "Anodische Bilanz": "Anodic Balance",
  Betriebsdaten: "Operating Data",
  DOL: "DOL",
  "Datenerfassung Elektrolyseure": "Input Standardized Voltage Electrolyzer",
  "Datenerfassung Elemente": "Input Standardized Voltage Elements",
  DiaGruppe: "Group Diagram",
  DiaUnCEA: "Un / CE Diagram",
  Einzelteile: "Cell Components",
  Energieverbrauch: "Power Consumption",
  "Electrode Segregation (TAFKIK)": "Electrode Segregation (TAFKIK)",
  Formular1: "Form 1",
  "Gesamt Norm >90": "Elements > 90°",
  "Gesamt Normierung": "Standardized Voltage All Elements",
  Gruppen: "Groups",
  "Gruppen Übersicht": "Group Overview",
  Gruppenmerkmale: "Group Definition",
  Header: "Header",
  ListGrGes: "Group List (Total)",
  "Norm(Um)AlleDatum": "Norm (Um) All Dates",
  "Norm(Um)DatMittel": "Norm (Um) Date Average",
  "Norm(Um)ElekDatum": "Norm (Um) Electrolyzer Date",
  NormElekGes: "Norm Electrolyzer Total",
  "Recoating Anoden": "Anode Recoating",
  "Recoating Kathoden": "Cathode Recoating",
  Remembraning: "Remembraning",
  Spannug2: "Voltage",
  Suchübersicht: "Search Overview",
  Um: "Standardized Voltage",
  UnCE: "Un / CE",
  frmAboutEAP: "About EAP",
  frmAbschaltungen: "Shut Down List",
  frmAbschaltungenZeitraum: "Shut Downs in Time Period",
  frmAbschaltungsUrsachen: "Shut Down Reasons",
  frmAbschaltungskategorien: "Shut Down Categories",
  frmAbschaltungszusammenfassung: "Shut Down Summary (Code/Reason)",
  frmAbschaltungszusammenfassungKategorie: "Shut Down Summary (Category)",
  frmMenuAbschaltungen: "Shut Down Menu",
  frmAnalyseAnolytEinlesen: "Read Anolyte Analyses from File",
  frmAnalyseHClElektrolyseur: "HCl Analysis Electrolyzer",
  frmAnalyseHClGesamtanlage: "HCl Analysis Plant",
  frmAnalyseHClTeilanlage: "HCl Analysis Sub-Plant",
  frmAnalysenEinlesen: "Import Analyses",
  frmAnodencoatingpruefung: "Check Anode Coating",
  frmAnodendetails: "Anode Details",
  frmAnodeninstandhaltung: "Anode Maintenance",
  frmAnodenrecoating: "Anode Recoating",
  frmAnordnung: "Cell Arrangement",
  frmBemerkungen: "Remarks",
  frmDateneinlesenElemente: "Read Element Voltages from File",
  frmDateneinlesenElementeAlt: "Read Element Voltages from File (Alt)",
  frmEinstellungen: "Settings",
  frmElementinspektion: "Element Inspection",
  frmEnergieverbrauchDurchschnitt: "Average Power Consumption",
  frmImportDemontagedaten: "Import Disassembly Data",
  frmImportMontagedaten: "Import Assembly Data",
  frmInspektionsBerichtAlt: "Inspection Report (Alt)",
  frmInspektionsbericht: "Inspection Report",
  frmInspektionsberichtBefunde: "Inspection Report Findings",
  frmInspektionsberichtTest: "Inspection Report (Test)",
  frmInspektionsgruende: "Reasons for Inspection",
  frmInspektionsgruende2: "Reasons for Inspection 2",
  frmInspektionsgruendeMontage: "Reasons for Inspection (Assembly)",
  frmInspektionsprotokollMembranAS: "Membrane Inspection Protocol (AS)",
  frmKathodencoatingpruefung: "Check Cathode Coating",
  frmKathodendetails: "Cathode Details",
  frmKathodeninstandhaltung: "Cathode Maintenance",
  frmKathodenrecoating: "Cathode Recoating",
  frmLagerbestandAnoden: "Anode Stock",
  frmLagerbestandKathoden: "Cathode Stock",
  frmLagerbestandMembranen: "Membrane Stock",
  frmMembrandetails: "Membrane Details",
  frmMembrandetails2: "Membrane Details 2",
  frmMembraninstandhaltung: "Membrane Maintenance",
  frmMembranstatistik: "Membrane Statistics",
  frmMenuStatistik: "Statistics Menu",
  frmMontagedaten: "Assembly Data",
  frmMontagedatenSuchergebnis: "Assembly Data Search Result",
  frmReinstsoleAnUebertragen: "Transfer Pure Brine Analyses",
  frmStatistikAbweichungUn: "Voltage Deviation Statistics",
  frmStatistikVerteilungUN: "Voltage Distribution Statistics",
  frmTabelleLeistungstests: "Performance Test Results",
  frmTabelleSPC: "SPC Table",
  frmZellenverwaltung: "Element Administration",
  frmEingabeUnElement: "Input Un Element",
  frmEingabeUnGruppe: "Input Un Group",
  subfrmAnlageAnzeigen: "Plant Header",
  subfrmAnlageAnzeigen2: "Plant Header 2",
  subfrmAnlagentyp: "Plant Type",
  subfrmElektrolyseurbezeichnung: "Electrolyzer Name",
  subfrmGleichrichterbezeichnung: "Rectifier Name",
  subfrmTransformatorbezeichnung: "Transformer Name",
  subfrmTeilanlagenbezeichnung: "Sub-Plant Name",
  subfrmFlaeche: "Electrode Area",
  subfrmKunde: "Client",
  subfrmSprache: "Language",
  subfrmSpannung: "Voltage",
  subfrmAuswertungszeitraum: "Evaluation Period",
  subfrmUnCE1: "Un / CE Selector",
  subfrmSPC1: "SPC Selector",
  subfrmGruppeCE: "Group CE",
  subfrmGruppeSPC: "Group SPC",
  subfrmGruppeUN: "Group Un",
  subfrmGruppenCE: "Groups CE",
  subfrmGruppenSPC: "Groups SPC",
  subfrmGruppenUN: "Groups Un",
  subfrmElektrolyseurCEElement: "Electrolyzer CE Element",
  subfrmElektrolyseurCEElemente: "Electrolyzer CE Elements",
  subfrmElektrolyseurSPCElement: "Electrolyzer SPC Element",
  subfrmElektrolyseurSPCElemente: "Electrolyzer SPC Elements",
  subfrmElektrolyseurUN: "Electrolyzer Un",
  subfrmElektrolyseurUnElement: "Electrolyzer Un Element",
  subfrmElektrolyseurUnElemente: "Electrolyzer Un Elements",
  subfrmElektrolyseurVerteilungUN: "Electrolyzer Un Distribution",
  subfrmElektrolyseureCE: "Electrolyzers CE",
  subfrmElektrolyseureSPC: "Electrolyzers SPC",
  subfrmElektrolyseureUN: "Electrolyzers Un",
  subfrmElektrolyseureUnCeSpc: "Electrolyzers Un / CE / SPC",
  subfrmInfoDateienAnalysen: "Analysis Files Info",
  subfrmInfoDateienUElemente: "Element Voltage Files Info",
  subfrmInfoEingeleseneAnalysen: "Imported Analyses Info",
  subfrmInfoEingeleseneUElemente: "Imported Element Voltages Info",
  subfrmInfoUebertrageneAnalysen: "Transferred Analyses Info",
  subfrmInfoUebertrageneReinstsoleAnalysen: "Transferred Pure Brine Analyses Info",
  subfrmInspektionsberichtAnodenhalbschale: "Inspection Report Anode Half-Shell",
  subfrmInspektionsberichtKathodenhalbschale: "Inspection Report Cathode Half-Shell",
  subfrmInspektionsberichtMembranAS: "Inspection Report Membrane AS",
  subfrmInspektionsberichtMembranKS: "Inspection Report Membrane KS",
  subfrmInspektionsberichtMembranLT: "Inspection Report Membrane LT",
  subfrmInspektionsberichtBefunde: "Inspection Findings",
  subfrmInspektionsberichtDrucken: "Print Inspection Report",
  subfrmSucheAbschaltungenZeitraum: "Search Shut Downs Time Period",
  subfrmSuchergebnisAbschaltungenZeitraum: "Shut Downs Time Period Result",
  subfrmEnergieverbrauchDurchschnitt: "Average Power Consumption Filter",
  subfrmEnergieverbrauchDurchschnittErgebnis: "Average Power Consumption Result",
  subfrmAKFEingabe: "Anodic Correction Factor Input",
  subfrmAnsaeurung: "Acidification",
  subfrmKorrekturfaktoren: "Correction Factors",
  subfrmReserveplaetze: "Reserve Positions",
  subfrmReserveplaetzeEinlesen: "Import Reserve Positions",
  tblImportKathodeninstandhaltung: "Import Cathode Maintenance",
  tblImportMontage: "Import Assembly",
};

/** Longer German tokens first so compound names translate cleanly. */
const TOKENS: [RegExp, string][] = [
  [/AbschaltungszusammenfassungKategorie/gi, "ShutDownSummaryCategory"],
  [/Abschaltungszusammenfassung/gi, "ShutDownSummary"],
  [/Abschaltungskategorien/gi, "ShutDownCategories"],
  [/AbschaltungsUrsachen/gi, "ShutDownReasons"],
  [/Abschaltungsursachen/gi, "ShutDownReasons"],
  [/AbschaltungenZeitraum/gi, "ShutDownsTimePeriod"],
  [/Abschaltungen/gi, "ShutDowns"],
  [/Abschaltungs/gi, "ShutDown"],
  [/Abschalt/gi, "ShutDown"],
  [/Leistungstests/gi, "PerformanceTests"],
  [/EnergieverbrauchDurchschnitt/gi, "AveragePowerConsumption"],
  [/Energieverbrauch/gi, "PowerConsumption"],
  [/Datenerfassung/gi, "DataEntry"],
  [/Betriebsdaten/gi, "OperatingData"],
  [/Einzelteile/gi, "CellComponents"],
  [/Suchübersicht/gi, "SearchOverview"],
  [/Anodische.?Bilanz/gi, "AnodicBalance"],
  [/Gruppenmerkmale/gi, "GroupDefinition"],
  [/Gruppen.?Übersicht/gi, "GroupOverview"],
  [/Gesamtanlage/gi, "TotalPlant"],
  [/Teilanlagen/gi, "SubPlants"],
  [/Teilanlage/gi, "SubPlant"],
  [/ElektrolyseureUnCeSpc/gi, "ElectrolyzersUnCeSpc"],
  [/Elektrolyseure/gi, "Electrolyzers"],
  [/Elektrolyseurbezeichnung/gi, "ElectrolyzerName"],
  [/Elektrolyseur/gi, "Electrolyzer"],
  [/Gleichrichterbezeichnung/gi, "RectifierName"],
  [/Transformatorbezeichnung/gi, "TransformerName"],
  [/Teilanlagenbezeichnung/gi, "SubPlantName"],
  [/Anodenhalbschale/gi, "AnodeHalfShell"],
  [/Kathodenhalbschale/gi, "CathodeHalfShell"],
  [/Uebertragene/gi, "Transferred"],
  [/Übertragene/gi, "Transferred"],
  [/Eingelesene/gi, "Imported"],
  [/Dateien/gi, "Files"],
  [/Flaeche/gi, "Area"],
  [/Fläche/gi, "Area"],
  [/bezeichnung/gi, "Name"],
  [/Elemente/gi, "Elements"],
  [/Elementinspektion/gi, "ElementInspection"],
  [/Element/gi, "Element"],
  [/Anodenrecoating/gi, "AnodeRecoating"],
  [/Anodeninstandhaltung/gi, "AnodeMaintenance"],
  [/Anodencoatingpruefung/gi, "AnodeCoatingCheck"],
  [/Anodendetails/gi, "AnodeDetails"],
  [/Anoden/gi, "Anodes"],
  [/Kathodenrecoating/gi, "CathodeRecoating"],
  [/Kathodeninstandhaltung/gi, "CathodeMaintenance"],
  [/Kathodencoatingpruefung/gi, "CathodeCoatingCheck"],
  [/Kathodendetails/gi, "CathodeDetails"],
  [/Kathoden/gi, "Cathodes"],
  [/Membraninstandhaltung/gi, "MembraneMaintenance"],
  [/Membrandetails/gi, "MembraneDetails"],
  [/Membranstatistik/gi, "MembraneStatistics"],
  [/Membranen/gi, "Membranes"],
  [/Membran/gi, "Membrane"],
  [/InspektionsberichtBefunde/gi, "InspectionFindings"],
  [/Inspektionsbericht/gi, "InspectionReport"],
  [/Inspektionsprotokoll/gi, "InspectionProtocol"],
  [/Inspektionsgruende/gi, "InspectionReasons"],
  [/Inspektion/gi, "Inspection"],
  [/Lagerbestand/gi, "Stock"],
  [/Montagedaten/gi, "AssemblyData"],
  [/Demontagedaten/gi, "DisassemblyData"],
  [/Montage/gi, "Assembly"],
  [/Demontage/gi, "Disassembly"],
  [/Zellenverwaltung/gi, "ElementAdministration"],
  [/Einstellungen/gi, "Settings"],
  [/Anordnung/gi, "Arrangement"],
  [/Bemerkungen/gi, "Remarks"],
  [/AnalysenEinlesen/gi, "ImportAnalyses"],
  [/Analysen/gi, "Analyses"],
  [/Analyse/gi, "Analysis"],
  [/Anolyt/gi, "Anolyte"],
  [/Katholyt/gi, "Catholyte"],
  [/Reinstsole/gi, "PureBrine"],
  [/Reinsole/gi, "PureBrine"],
  [/Chlorgas/gi, "ChlorineGas"],
  [/Diagramm/gi, "Chart"],
  [/Tabelle/gi, "Table"],
  [/Eingabe/gi, "Input"],
  [/Statistik/gi, "Statistics"],
  [/Verteilung/gi, "Distribution"],
  [/Abweichung/gi, "Deviation"],
  [/Durchschnitt/gi, "Average"],
  [/Normierung/gi, "Normalization"],
  [/Suchergebnis/gi, "SearchResult"],
  [/Suche/gi, "Search"],
  [/aktive/gi, "Active"],
  [/passive/gi, "Passive"],
  [/Duplikate/gi, "Duplicates"],
  [/Inbetriebgenommene/gi, "Commissioned"],
  [/Ausgeschaltete/gi, "Decommissioned"],
  [/Demontierte/gi, "Disassembled"],
  [/Montierte/gi, "Assembled"],
  [/Ausschaltdatum/gi, "DecommissionDate"],
  [/Einschaltdatum/gi, "CommissionDate"],
  [/Demontagedatum/gi, "DisassemblyDate"],
  [/Montagedatum/gi, "AssemblyDate"],
  [/Gruppen/gi, "Groups"],
  [/Gruppe/gi, "Group"],
  [/Mehrere/gi, "Several"],
  [/Alle/gi, "All"],
  [/Gesamt/gi, "Total"],
  [/Ursachen/gi, "Reasons"],
  [/Ursache/gi, "Reason"],
  [/Kategorien/gi, "Categories"],
  [/Kategorie/gi, "Category"],
  [/Zeitraum/gi, "TimePeriod"],
  [/Zusammenfassung/gi, "Summary"],
  [/Einlesen/gi, "Import"],
  [/Uebertragen/gi, "Transfer"],
  [/Übertragen/gi, "Transfer"],
  [/Informationen?/gi, "Information"],
  [/nummer/gi, "Number"],
  [/Nummer/gi, "Number"],
  [/details/gi, "Details"],
  [/Details/gi, "Details"],
  [/Menu/gi, "Menu"],
  [/Menue/gi, "Menu"],
];

function splitCamel(text: string): string {
  return text
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function translateCompound(raw: string): string {
  let s = raw;
  for (const [re, repl] of TOKENS) {
    s = s.replace(re, repl);
  }
  return splitCamel(s);
}

export function accessFormEnglishLabel(name: string): string {
  if (EXACT[name]) return EXACT[name];

  let body = name;
  let prefix = "";
  if (/^subfrm/i.test(body)) {
    prefix = "";
    body = body.slice(6);
  } else if (/^frm/i.test(body)) {
    prefix = "";
    body = body.slice(3);
  } else if (/^tbl/i.test(body)) {
    prefix = "";
    body = body.slice(3);
  }

  const translated = translateCompound(body);
  // Keep already-English / acronym-heavy names readable
  if (!translated || translated === body) {
    return splitCamel(name.replace(/^(frm|subfrm|tbl)/i, "")) || name;
  }
  return prefix ? `${prefix} ${translated}` : translated;
}
